"""
Password-based auth gate for the agency dashboard + webhook protection.

Design notes
============
- Flask session cookie (HttpOnly, SameSite=Lax). Secure flag is toggled on
  automatically when `agent.tracking.base_url` starts with https://, which is
  the running app's own externally-reachable URL.
- CSRF is mitigated by SameSite=Lax AND the requirement that mutating
  endpoints (login, install, change-password) accept only
  Content-Type: application/json. Cross-origin form-encoded CSRF cannot
  trigger them because the browser refuses to send the cookie on a
  cross-site form POST.
- bcrypt cost=12 for password hashing.
- First-boot install endpoint is gated by a one-time setup token. The
  orchestrator stashes that token in a disk file (mode 0o600) at
  `data/last_install_token.txt` and ALSO emits it once to LOG.warning.
  Wizard step asks the operator to paste it back alongside the new password.
- `/run-audit` and `/new-lead` are NOT part of `/api/*` (they live on the
  app object directly), so they aren't covered by the blueprint auth gate.
  They're instead gated by an `?token=<webhook_secret>` query param, where
  `webhook_secret` lives in `settings.webhook_secret` and is generated by
  the orchestrator on first boot.
"""
from __future__ import annotations

import bcrypt
import logging
import secrets
import stat
from pathlib import Path
from typing import Any

from flask import Blueprint, jsonify, request, session

from . import db

LOG = logging.getLogger("ai_agency.auth")

auth_bp = Blueprint("auth", __name__, url_prefix="/api/auth")

# ── Pure JSON helpers (don't import app._ok to avoid a circular import) ────

def _ok(payload: Any = None, **extra: Any):
    out: dict[str, Any] = {"ok": True}
    if payload is not None:
        out["data"] = payload
    out.update(extra)
    return jsonify(out)


def _err(msg: str, code: int = 400):
    return jsonify({"ok": False, "error": msg}), code


# ── Settings helpers ──────────────────────────────────────────────────────

def _auth_setting() -> dict[str, Any]:
    return db.get_setting("auth") or {}


def _webhook_secret() -> str:
    s = db.get_setting("webhook_secret")
    return (s or {}).get("value") if isinstance(s, dict) else (s or "")


def is_installed() -> bool:
    return bool(_auth_setting().get("password_hash"))


def is_authed() -> bool:
    return bool(session.get("authed"))


# ── Bootstrap helpers (called from app.py boot) ──────────────────────────

def generate_setup_token_if_uninstalled() -> str | None:
    """If auth is not installed yet, generate a one-time setup token, persist
    it (with TTL) to settings.auth_pending_setup_token, write it to a 0600
    file for the operator to find, and LOG a WARNING with the token. Returns
    None when already installed.
    """
    if is_installed():
        return None
    pending = db.get_setting("auth_pending_setup_token") or {}
    # Reuse an existing un-expired token so the wizard can poll
    # /api/auth/install-token without churning tokens.
    import time as _time
    now = int(_time.time())
    if isinstance(pending, dict) and pending.get("value") and pending.get("expires_at", 0) > now:
        return pending["value"]
    token = secrets.token_urlsafe(9)  # 12 chars, URL-safe
    db.set_setting("auth_pending_setup_token", {
        "value": token,
        "issued_at": now,
        "expires_at": now + 30 * 60,  # 30 min TTL
    })
    # Persist to a 0o600 file so the operator can `cat` it if they missed
    # the WARN line.
    try:
        token_path = Path(db.DATA_DIR) / "last_install_token.txt"
        token_path.write_text(token + "\n")
        token_path.chmod(stat.S_IRUSR | stat.S_IWUSR)
    except OSError as exc:
        LOG.warning("could not write install token to disk: %s", exc)
    LOG.warning(
        "AUTH NOT INSTALLED. One-time setup token: %s "
        "(valid 30 min; also written to data/last_install_token.txt). "
        "Paste it into /wizard step 0 to set the dashboard password.",
        token,
    )
    return token


def ensure_webhook_secret() -> str:
    """Make sure the webhook secret exists. Returns it. Generates on first
    boot only; never rotates silently."""
    existing = _webhook_secret()
    if existing:
        return existing
    secret = secrets.token_urlsafe(24)  # 32 chars
    db.set_setting("webhook_secret", {"value": secret, "issued_at": db._now()})
    LOG.warning(
        "Generated webhook_secret on first boot. Use it on the "
        "public URLs /run-audit?token=... and /new-lead?token=... "
        "(also: GET /api/webhook/url shows it to logged-in operators)."
    )
    return secret


# ── Endpoints ────────────────────────────────────────────────────────────

@auth_bp.route("/status", methods=["GET"])
def status():
    pending = db.get_setting("auth_pending_setup_token")
    has_pending = bool(
        pending
        and isinstance(pending, dict)
        and pending.get("value")
        and pending.get("expires_at", 0) > __import__("time").time()
    )
    return _ok({
        "installed": is_installed(),
        "authed": is_authed(),
        "has_pending_setup_token": has_pending,
    })


@auth_bp.route("/install-token", methods=["GET"])
def install_token():
    """Either returns a fresh one-time token (and stores it with TTL), or
    returns the still-valid one if it was issued within TTL. This endpoint
    is what the wizard polls on so the operator can paste whatever's shown
    in the wizard modal into the password step."""
    if is_installed():
        return _err("already_installed", 409)
    token = generate_setup_token_if_uninstalled()
    assert token is not None  # we just guarded the inverse
    return _ok({
        "setup_token": token,
        "expires_in_minutes": 30,
        "note": "Paste this into Step 0 of the wizard along with your password.",
    })


@auth_bp.route("/install", methods=["POST"])
def install():
    """Set the dashboard password for the first time using the one-time
    setup token. After this call the install token is invalidated and
    install-token endpoint will start returning 409."""
    if is_installed():
        return _err("already_installed", 403)
    body = request.get_json(silent=True) or {}
    setup_token = (body.get("setup_token") or "").strip()
    pw = body.get("password") or ""
    pw2 = body.get("password_confirm") or ""
    if len(pw) < 8:
        return _err("password_too_short_min_8", 422)
    if pw != pw2:
        return _err("password_confirm_mismatch", 422)
    pending = db.get_setting("auth_pending_setup_token") or {}
    import time as _time
    if not (isinstance(pending, dict)
            and pending.get("value") == setup_token
            and pending.get("expires_at", 0) > _time.time()):
        return _err("invalid_or_expired_setup_token", 422)
    # bcrypt hashing time is ~250ms on cost=12; do it before clearing the token.
    ph = bcrypt.hashpw(pw.encode("utf-8"), bcrypt.gensalt(rounds=12)).decode("ascii")
    db.set_setting("auth", {
        "password_hash": ph,
        "installed_at": db._now(),
        "scheme": "bcrypt-12",
    })
    # Invalidate the pending token (don't leave a usable token in settings).
    db.set_setting("auth_pending_setup_token", {"value": "", "expires_at": 0})
    db.audit("auth.installed", {"scheme": "bcrypt-12"})
    # Auto-login the operator right after install so the wizard doesn't have
    # to make a second round-trip.
    session.clear()
    session["authed"] = True
    session["login_at"] = db._now()
    return _ok({"installed": True, "authed": True})


@auth_bp.route("/login", methods=["POST"])
def login():
    if not is_installed():
        return _err("auth_not_installed_use_wizard", 422)
    body = request.get_json(silent=True) or {}
    pw = body.get("password") or ""
    if not pw:
        return _err("password_required", 422)
    stored = _auth_setting().get("password_hash") or ""
    if not stored:
        return _err("server_state_error_no_hash", 500)
    try:
        ok = bcrypt.checkpw(pw.encode("utf-8"), stored.encode("ascii"))
    except (ValueError, TypeError):
        ok = False
    if not ok:
        # Constant-time-ish: we already paid the bcrypt cost even on failure,
        # so the timing of an invalid attempt isn't materially different.
        return _err("invalid_credentials", 401)
    session.clear()
    session["authed"] = True
    session["login_at"] = db._now()
    db.audit("auth.login_ok", {})
    return _ok({"authed": True})


@auth_bp.route("/logout", methods=["POST"])
def logout():
    was = session.get("authed")
    session.clear()
    if was:
        db.audit("auth.logout", {})
    return _ok({"authed": False})


@auth_bp.route("/change-password", methods=["POST"])
def change_password():
    """Change the dashboard password (requires current password). Lets the
    operator rotate without re-install and without exposing a generic
    unauthenticated endpoint to set arbitrary passwords."""
    if not is_authed():
        return _err("auth_required", 401)
    body = request.get_json(silent=True) or {}
    cur = body.get("current_password") or ""
    new = body.get("new_password") or ""
    new2 = body.get("new_password_confirm") or ""
    if len(new) < 8:
        return _err("password_too_short_min_8", 422)
    if new != new2:
        return _err("password_confirm_mismatch", 422)
    stored = _auth_setting().get("password_hash") or ""
    try:
        ok = bcrypt.checkpw(cur.encode("utf-8"), stored.encode("ascii"))
    except (ValueError, TypeError):
        ok = False
    if not ok:
        return _err("current_password_invalid", 401)
    ph = bcrypt.hashpw(new.encode("utf-8"), bcrypt.gensalt(rounds=12)).decode("ascii")
    db.set_setting("auth", {
        "password_hash": ph,
        "installed_at": _auth_setting().get("installed_at") or db._now(),
        "rotated_at": db._now(),
        "scheme": "bcrypt-12",
    })
    db.audit("auth.password_rotated", {})
    return _ok({"rotated": True})


# ── Webhook URL helper (logged-in operator only) ────────────────────────

@auth_bp.route("/webhook/url", methods=["GET"])
def webhook_url():
    if not is_authed():
        return _err("auth_required", 401)
    from .config import tracking_base_url
    base = tracking_base_url().rstrip("/")
    if not base:
        return _err(
            "tracking.base_url unset — set it in step 5 of /wizard before "
            "the webhook URLs are useful.",
            422,
        )
    sec = _webhook_secret()
    # Show first 4 + last 4 of the secret for visual confirmation; don't
    # leak the whole thing in case it ends up in a screenshot.
    masked = (sec[:4] + "…" + sec[-4:]) if len(sec) >= 9 else "set"
    return _ok({
        "run_audit_url": f"{base}/run-audit?token={sec}",
        "new_lead_url": f"{base}/new-lead?token={sec}",
        "secret_masked": masked,
    })
